#!/bin/sh
carton install --deployment

cd /opt
## Runtime
zip -r /zips/perl-runtime.zip perl bootstrap -x *.pod

## Paws
ln -s /root/local/ /opt/perl/carton 
zip -r /zips/perl-paws.zip perl/carton/lib perl/carton/bin -x *.pod